//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_SM_HisData_00001
    {
        public System.DateTime RecTime { get; set; }
        public int TagID { get; set; }
        public int PID { get; set; }
        public Nullable<double> PV { get; set; }
        public string AlarmStatus { get; set; }
        public Nullable<double> AlarmLimits { get; set; }
    }
}
